# Generated by Django 5.1.1 on 2024-10-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
