# Generated by Django 5.1.1 on 2024-10-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
