# Generated by Django 5.1.1 on 2024-10-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
    ]
